// Mock data for development — all data that would normally come from backend API

export const mockCurrentUser = {
    id: 'user-1',
    firstName: 'Priya',
    lastName: 'Mehta',
    email: 'priya@bits.ac.in',
    role: 'student', // Change to 'teacher' to see teacher views
    college: 'BITS Pilani',
    year: '3rd Year',
    department: 'Computer Science',
    avatar: null,
    bio: 'Passionate about learning new technologies and building cool projects.',
    subjects: ['react', 'javascript', 'python'],
    teachingSubjects: ['react', 'javascript', 'python'],
    memberSince: '2025-01-15',
    sessionsAsStudent: 12,
    sessionsAsTeacher: 8,
    avgRating: 4.8,
    isOnline: true,
    notifications: { messages: 3, requests: 5 },
};

export const mockTeachers = [
    {
        id: 'teacher-1',
        firstName: 'Raj',
        lastName: 'Sharma',
        name: 'Raj Sharma',
        email: 'raj@iiith.ac.in',
        college: 'IIIT Hyderabad',
        year: '3rd Year',
        department: 'Computer Science',
        avatar: null,
        bio: 'Full-stack developer with 3+ years of experience in React and Node.js. Love helping others understand complex concepts through practical examples and real-world projects.',
        subjects: ['react', 'javascript', 'python', 'nodejs'],
        rating: 4.9,
        totalSessions: 52,
        studentsHelped: 47,
        responseTime: '< 2 hours',
        isVerified: true,
        isOnline: true,
        availability: {
            Mon: ['morning', 'evening'],
            Tue: ['afternoon', 'evening'],
            Wed: ['morning', 'afternoon'],
            Thu: ['evening', 'night'],
            Fri: ['morning', 'afternoon', 'evening'],
            Sat: ['morning', 'afternoon'],
            Sun: ['evening'],
        },
    },
    {
        id: 'teacher-2',
        firstName: 'Sneha',
        lastName: 'Patel',
        name: 'Sneha Patel',
        college: 'IIT Bombay',
        year: '4th Year',
        department: 'Physics',
        avatar: null,
        bio: 'Physics enthusiast specializing in Thermodynamics and Quantum Mechanics. I break down complex theories into simple, intuitive explanations.',
        subjects: ['physics', 'math', 'chemistry'],
        rating: 4.8,
        totalSessions: 38,
        studentsHelped: 32,
        responseTime: '< 1 hour',
        isVerified: true,
        isOnline: true,
    },
    {
        id: 'teacher-3',
        firstName: 'Arjun',
        lastName: 'Kumar',
        name: 'Arjun Kumar',
        college: 'NIT Trichy',
        year: '2nd Year',
        department: 'Computer Science',
        avatar: null,
        bio: 'Competitive programmer ranked in top 500 on CodeChef. I teach DSA from basics to advanced topics.',
        subjects: ['dsa', 'python', 'cs'],
        rating: 4.7,
        totalSessions: 29,
        studentsHelped: 25,
        responseTime: '< 3 hours',
        isVerified: true,
        isOnline: false,
    },
    {
        id: 'teacher-4',
        firstName: 'Meera',
        lastName: 'Joshi',
        name: 'Meera Joshi',
        college: 'Delhi University',
        year: '3rd Year',
        department: 'Mathematics',
        avatar: null,
        bio: 'Mathematics major with a passion for Statistics and Probability. Tutoring since my freshman year.',
        subjects: ['math', 'statistics', 'economics'],
        rating: 4.6,
        totalSessions: 22,
        studentsHelped: 19,
        responseTime: '< 4 hours',
        isVerified: false,
        isOnline: true,
    },
    {
        id: 'teacher-5',
        firstName: 'Vikram',
        lastName: 'Singh',
        name: 'Vikram Singh',
        college: 'VIT Vellore',
        year: '4th Year',
        department: 'Computer Science',
        avatar: null,
        bio: 'ML/AI researcher with published papers. I simplify Machine Learning for everyone.',
        subjects: ['ml', 'python', 'statistics', 'math'],
        rating: 4.9,
        totalSessions: 45,
        studentsHelped: 40,
        responseTime: '< 2 hours',
        isVerified: true,
        isOnline: false,
    },
    {
        id: 'teacher-6',
        firstName: 'Aisha',
        lastName: 'Khan',
        name: 'Aisha Khan',
        college: 'BITS Goa',
        year: '3rd Year',
        department: 'Electronics',
        avatar: null,
        bio: 'Electronics and embedded systems enthusiast. I make circuits fun!',
        subjects: ['electronics', 'physics', 'math'],
        rating: 4.5,
        totalSessions: 15,
        studentsHelped: 12,
        responseTime: '< 5 hours',
        isVerified: true,
        isOnline: true,
    },
];

export const mockRequests = [
    {
        id: 'req-1',
        student: { id: 'student-1', name: 'Ananya Sharma', college: 'Delhi University', avatar: null },
        subject: 'physics',
        topic: 'Thermodynamics — Second Law & Entropy',
        description: 'I have my mid-semester exam in 3 days and I\'m struggling with entropy calculations and Carnot cycle problems. Need someone to walk me through the concepts with examples.',
        urgency: 'exam-soon',
        examDate: '2026-02-22',
        preferredTime: ['evening'],
        dayPreference: 'weekdays',
        postedAt: '2026-02-19T08:30:00',
        status: 'pending',
        attachment: null,
    },
    {
        id: 'req-2',
        student: { id: 'student-2', name: 'Karthik Reddy', college: 'BITS Pilani', avatar: null },
        subject: 'react',
        topic: 'React Hooks & State Management',
        description: 'Want to understand useEffect, useCallback, and useMemo properly. I keep getting infinite re-renders in my project.',
        urgency: 'urgent',
        preferredTime: ['afternoon', 'evening'],
        dayPreference: 'any',
        postedAt: '2026-02-18T14:20:00',
        status: 'pending',
        attachment: null,
    },
    {
        id: 'req-3',
        student: { id: 'student-3', name: 'Neha Gupta', college: 'IIT Delhi', avatar: null },
        subject: 'dsa',
        topic: 'Dynamic Programming Patterns',
        description: 'I can solve basic DP problems but struggle with optimization problems. Looking for someone to practice medium-hard problems with.',
        urgency: 'normal',
        preferredTime: ['morning', 'afternoon'],
        dayPreference: 'weekends',
        postedAt: '2026-02-17T10:00:00',
        status: 'pending',
        attachment: null,
    },
    {
        id: 'req-4',
        student: { id: 'student-4', name: 'Rohit Verma', college: 'NIT Warangal', avatar: null },
        subject: 'python',
        topic: 'Python OOP Concepts',
        description: 'Need help understanding classes, inheritance, polymorphism and design patterns in Python.',
        urgency: 'normal',
        preferredTime: ['evening', 'night'],
        dayPreference: 'any',
        postedAt: '2026-02-18T20:00:00',
        status: 'pending',
        attachment: null,
    },
    {
        id: 'req-5',
        student: { id: 'student-5', name: 'Divya Nair', college: 'IIIT Bangalore', avatar: null },
        subject: 'ml',
        topic: 'Neural Networks from Scratch',
        description: 'Want to understand backpropagation and gradient descent intuitively. Exam next week!',
        urgency: 'exam-soon',
        examDate: '2026-02-25',
        preferredTime: ['morning'],
        dayPreference: 'weekdays',
        postedAt: '2026-02-19T06:00:00',
        status: 'pending',
        attachment: null,
    },
];

export const mockSessions = [
    {
        id: 'session-1',
        subject: 'physics',
        topic: 'Thermodynamics Chapter 6',
        teacher: { id: 'teacher-2', name: 'Sneha Patel', avatar: null },
        student: { id: 'user-1', name: 'Priya Mehta', avatar: null },
        startTime: '2026-02-20T17:00:00',
        endTime: '2026-02-20T18:00:00',
        status: 'upcoming',
        meetLink: 'https://meet.google.com/abc-defg-hij',
        notes: '',
        reviewed: false,
    },
    {
        id: 'session-2',
        subject: 'react',
        topic: 'Building Custom Hooks',
        teacher: { id: 'teacher-1', name: 'Raj Sharma', avatar: null },
        student: { id: 'user-1', name: 'Priya Mehta', avatar: null },
        startTime: '2026-02-21T10:00:00',
        endTime: '2026-02-21T11:00:00',
        status: 'upcoming',
        meetLink: 'https://meet.google.com/xyz-uvwx-abc',
        notes: '',
        reviewed: false,
    },
    {
        id: 'session-3',
        subject: 'dsa',
        topic: 'Binary Trees & BST',
        teacher: { id: 'teacher-3', name: 'Arjun Kumar', avatar: null },
        student: { id: 'user-1', name: 'Priya Mehta', avatar: null },
        startTime: '2026-02-19T14:00:00',
        endTime: '2026-02-19T15:00:00',
        status: 'ongoing',
        meetLink: 'https://meet.google.com/meet-live-123',
        notes: '',
        reviewed: false,
    },
    {
        id: 'session-4',
        subject: 'javascript',
        topic: 'Closures & Prototypes',
        teacher: { id: 'teacher-1', name: 'Raj Sharma', avatar: null },
        student: { id: 'user-1', name: 'Priya Mehta', avatar: null },
        startTime: '2026-02-15T16:00:00',
        endTime: '2026-02-15T17:30:00',
        status: 'completed',
        meetLink: null,
        notes: 'Great session! Covered closures in depth with practical examples. Need to review prototype chain again.',
        reviewed: true,
    },
    {
        id: 'session-5',
        subject: 'python',
        topic: 'Data Structures in Python',
        teacher: { id: 'teacher-5', name: 'Vikram Singh', avatar: null },
        student: { id: 'user-1', name: 'Priya Mehta', avatar: null },
        startTime: '2026-02-12T11:00:00',
        endTime: '2026-02-12T12:00:00',
        status: 'completed',
        meetLink: null,
        notes: '',
        reviewed: false,
    },
];

export const mockMessages = [
    {
        id: 'conv-1',
        with: { id: 'teacher-1', name: 'Raj Sharma', avatar: null, isOnline: true, subject: 'React' },
        messages: [
            { id: 'm1', senderId: 'teacher-1', text: 'Hi Priya! I saw your request for React hooks help.', timestamp: '2026-02-19T10:30:00', read: true },
            { id: 'm2', senderId: 'user-1', text: 'Yes! I\'m struggling with useEffect cleanup functions.', timestamp: '2026-02-19T10:32:00', read: true },
            { id: 'm3', senderId: 'teacher-1', text: 'No worries, it\'s a common confusion. Let me set up a session for us.', timestamp: '2026-02-19T10:33:00', read: true },
            { id: 'm4', senderId: 'teacher-1', text: 'How about tomorrow at 5 PM?', timestamp: '2026-02-19T10:34:00', read: true },
            { id: 'm5', senderId: 'user-1', text: 'That works perfectly! Thank you so much 🙏', timestamp: '2026-02-19T10:35:00', read: true },
            {
                id: 'm6', senderId: 'teacher-1', type: 'meet-link',
                text: 'Study Room Ready 🎥',
                meetLink: 'https://meet.google.com/abc-defg-hij',
                timestamp: '2026-02-19T10:36:00', read: false
            },
        ],
        lastMessage: 'Study Room Ready 🎥',
        lastMessageTime: '2026-02-19T10:36:00',
        unreadCount: 1,
        urgency: null,
    },
    {
        id: 'conv-2',
        with: { id: 'teacher-2', name: 'Sneha Patel', avatar: null, isOnline: true, subject: 'Physics' },
        messages: [
            { id: 'm7', senderId: 'user-1', text: 'Hi Sneha, I need urgent help with Thermodynamics!', timestamp: '2026-02-19T08:00:00', read: true, urgency: 'urgent' },
            { id: 'm8', senderId: 'teacher-2', text: 'Sure! When is your exam?', timestamp: '2026-02-19T08:15:00', read: true },
            { id: 'm9', senderId: 'user-1', text: 'It\'s on February 22nd 😰', timestamp: '2026-02-19T08:16:00', read: true },
            { id: 'm10', senderId: 'teacher-2', text: 'Don\'t worry, we have enough time. Let\'s schedule sessions for the next 2 days. I\'ll cover entropy and Carnot cycle.', timestamp: '2026-02-19T08:20:00', read: false },
        ],
        lastMessage: "Don't worry, we have enough time...",
        lastMessageTime: '2026-02-19T08:20:00',
        unreadCount: 1,
        urgency: 'urgent',
    },
    {
        id: 'conv-3',
        with: { id: 'teacher-3', name: 'Arjun Kumar', avatar: null, isOnline: false, subject: 'DSA' },
        messages: [
            { id: 'm11', senderId: 'teacher-3', text: 'Your session is confirmed for today at 2 PM!', timestamp: '2026-02-19T09:00:00', read: true },
            { id: 'm12', senderId: 'user-1', text: 'Great, see you then!', timestamp: '2026-02-19T09:05:00', read: true },
        ],
        lastMessage: 'Great, see you then!',
        lastMessageTime: '2026-02-19T09:05:00',
        unreadCount: 0,
        urgency: null,
    },
];

export const mockReviews = [
    {
        id: 'rev-1',
        reviewer: { name: 'Priya Mehta', college: 'BITS Pilani', avatar: null },
        rating: 5,
        text: 'Raj is an amazing teacher! He explained React hooks so clearly with practical examples. Highly recommend for anyone learning frontend development.',
        date: '2026-02-15',
        subject: 'React',
    },
    {
        id: 'rev-2',
        reviewer: { name: 'Ananya Sharma', college: 'Delhi University', avatar: null },
        rating: 5,
        text: 'Extremely patient and knowledgeable. Helped me understand closures which I\'d been struggling with for weeks. Will definitely book more sessions.',
        date: '2026-02-10',
        subject: 'JavaScript',
    },
    {
        id: 'rev-3',
        reviewer: { name: 'Karthik Reddy', college: 'BITS Pilani', avatar: null },
        rating: 4,
        text: 'Good session on Node.js basics. Covered Express routing and middleware. Could have been a bit more organized but overall very helpful.',
        date: '2026-02-05',
        subject: 'Node.js',
    },
    {
        id: 'rev-4',
        reviewer: { name: 'Neha Gupta', college: 'IIT Delhi', avatar: null },
        rating: 5,
        text: 'Best Python teacher on the platform! Made OOP concepts so easy to understand. The real-world project examples were incredibly useful.',
        date: '2026-01-28',
        subject: 'Python',
    },
];

export const mockTestimonials = [
    {
        name: 'Ananya Sharma',
        college: 'Delhi University',
        text: '"SkilloCity changed how I study. Found an amazing Physics tutor who helped me ace my midterms. The urgency feature meant I got help within hours before my exam!"',
        rating: 5,
    },
    {
        name: 'Karthik Reddy',
        college: 'BITS Pilani',
        text: '"As a teacher on SkilloCity, I\'ve helped 30+ students while sharpening my own skills. The platform makes scheduling and connecting so seamless."',
        rating: 5,
    },
    {
        name: 'Priya Nair',
        college: 'IIT Madras',
        text: '"I love that it\'s completely free. No hidden charges, no premium tiers. Just students helping students. This is how education should be."',
        rating: 5,
    },
];
